sudo: required

language: node_js

node_js:
  - 8

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - master

before_install:
  - set -e
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g @angular/cli
- npm install -g karma

script:
  - npm run test
  - npm run e2e
  - ng build --prod --base-href /
